export const SET_FILTER_TERM = 'SET_FILTER_TERM';
export const SET_FILTER_PRICE = 'SET_FILTER_PRICE';
export const SORT_BY_PRICE = 'SORT_BY_PRICE';
export const ADD_API_DATA = 'ADD_API_DATA';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_PRODUCTS_QUANTITY = 'SET_PRODUCTS_QUANTITY';
